# данные для ядра
[core]
exchange_name = 'ftx'
instance_name = '2'
[configuration]
# Откуда загружать конфигурацию. Может быть три значения: agent, api, file.

source = 'file'

# эндпойнт для получения конфигурации от конфигуратора.
#api = {url = 'https://configurator.robotrade.io/ftx/1', params = {only_new = false}}
api = ["configurator.robotrade.io", "/ftx/2?only_new=false"]

# настройки работы протокола aeron
[aeron]
# настройки каналов откуда будем принимать данные
[aeron.subscribers]
# настройки канала куда будет приходить конфигурацию от агента
# ["channel", channel_id]	
agent = ["aeron:ipc", 1004]
# настройки каналов куда будем отправлять данные
[aeron.publishers]
# канал куда отправляем логи
logs = ["aeron:ipc", 2002]
# канал агента куда гейт при запуске отправит запрос на получение конфига
agent = ["aeron:ipc", 1002]
